#ifndef MEMCACHED_TRACE_H
#define MEMCACHED_TRACE_H

#define MEMCACHED_CONN_CREATE(arg0)
#define MEMCACHED_CONN_DESTROY(arg0)
#define MEMCACHED_CONN_ALLOCATE(arg0)
#define MEMCACHED_CONN_DISPATCH(arg0, arg1)
#define MEMCACHED_CONN_RELEASE(arg0)
#define MEMCACHED_ITEM_REMOVE(arg0, arg1, arg2)
#define MEMCACHED_PROCESS_COMMAND_END(arg0, arg1, arg2)
#define MEMCACHED_PROCESS_COMMAND_START(arg0, arg1, arg2)

#endif
